apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }} 
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}  
    service: {{ .Values.app.name }} 
spec:
  ports:
  - port: {{ .Values.service.port }} 
    name: http
    targetPort: {{ .Values.app.port }} 
{{- if eq .Values.service.type "NodePort" }}
    nodePort: {{ .Values.service.nodeport }}
{{- end }}
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app.name }}

