{{- if and (.Values.image.privateRegistry.enabled) (not .Values.image.privateRegistry.global) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.app.name }}-imagepullsecret
  namespace: {{ .Release.Namespace }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ template "secret" . }}
{{- end }}

